New Repository and second attempt
FredsephT32/Set-up-first-Portfolio pull request #1
Opened 2022-06-30 21:13 UTC by FredsephT32

My first repository had a lot of errors with the linters and the node.js and I decided to just create a new Repository

2022-06-30 22:23 UTC, MeqdamAlqudah requested changes
Hi @FredsephT32 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
![](https://media4.giphy.com/media/7SyGkO0kQWCfnUC47Y/200.webp?cid=ecf05e471w8e4o4lcisp0zs3j9kvtdiczvcvtkid2isga2ec&rid=200.webp&ct=g)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:23 UTC, MeqdamAlqudah commented on index.html
> +       </nav>
- [ ] Please The container of the toolbar section must be a `header` tag

- [ ] Please the  hamburger button must be on the right 
![image](https://user-images.githubusercontent.com/74744787/176787036-8866aff7-34ab-4fde-a216-e8316710c90e.png)

2022-06-30 22:23 UTC, MeqdamAlqudah commented on index.html
> +       </nav>
- [ ] Please the toolbar section should have the same margin-bottom right as  in the Figma design
![image](https://user-images.githubusercontent.com/74744787/176787448-e68f2d86-ef69-4f59-873d-373066ff9395.png)

2022-06-30 22:23 UTC, MeqdamAlqudah commented on index.html
> +
- [ ] Please must use a `ul` tag to group the list of icons, and `li` per icon; each icon has a link (`a` tag) 
as it is semantically better this in this way

2022-06-30 22:23 UTC, MeqdamAlqudah commented on index.html
> +          </div>
- [ ] Please ` let's connect` here should be a button not an h3 element

2022-06-30 22:23 UTC, MeqdamAlqudah commented on index.html
> +               <img src="Images/Peace-Emoji-Icon.svg"  alt="Peace Icon">
- [ ] Please use the same margin as in Figma design fix this weird space around the page
![image](https://user-images.githubusercontent.com/74744787/176788399-83cb20c9-efd6-46ad-b13f-c1e3bfa8bb0e.png)

2022-07-01 16:29 UTC, mwanawabangona approved these changes
## STATUS: APPROVED 🟢

## Hi @FredsephT32 👋,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉


<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @mwanawabangona in your question so I can receive the notification.

2022-07-01 16:29 UTC, mwanawabangona commented on index.html
> +       </header>
- [ ] `optional`
- [ ] please make the logo same color as the figma template see screenshot below

your image
![Screenshot from 2022-07-01 04-12-29](https://user-images.githubusercontent.com/66230306/176933122-96841e7c-6b81-491d-957c-d85136bbed83.png)

figma image
![Screenshot from 2022-07-01 04-18-11](https://user-images.githubusercontent.com/66230306/176933228-4062deb7-2a5f-41e2-9c53-cdfbfb7456a3.png)

2022-07-01 16:29 UTC, mwanawabangona commented on index.html
> +          </div>
- [ ] `optional`
- [ ] please make the button same color as the figma template see screenshot below

figma template
![Screenshot from 2022-07-01 04-14-58](https://user-images.githubusercontent.com/66230306/176933771-e4bb04e1-8ab7-432f-808a-f2ae8d5940e2.png)

your template
![Screenshot from 2022-07-01 04-12-43](https://user-images.githubusercontent.com/66230306/176933900-d45f8697-1d64-4fa6-a283-2ea3d9e793e4.png)

2022-07-01 16:47 UTC, merged